//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTDT()
        {
            this.LopDTs = new HashSet<LopDT>();
        }
    
        public int IDCTDT { get; set; }
        public Nullable<int> IDNganhHoc { get; set; }
        public Nullable<int> IDMonHoc { get; set; }
        public Nullable<int> KyHoc { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual NganhHoc NganhHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopDT> LopDTs { get; set; }
    }
}
