//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhi
    {
        public int IDHocPhi { get; set; }
        public Nullable<int> IDInfoKyHoc { get; set; }
        public Nullable<int> IDSinhVien { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Paid { get; set; }
        public string Status { get; set; }
    
        public virtual InfoKyHoc InfoKyHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
