//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KQHT
    {
        public int IDKQHT { get; set; }
        public Nullable<int> IDSinhVien { get; set; }
        public Nullable<int> IDLopDT { get; set; }
        public Nullable<double> DTP { get; set; }
        public Nullable<double> DT { get; set; }
        public Nullable<double> DTK { get; set; }
        public Nullable<bool> Pass { get; set; }
    
        public virtual LopDT LopDT { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
