//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NganhHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NganhHoc()
        {
            this.CTDTs = new HashSet<CTDT>();
            this.LopHocs = new HashSet<LopHoc>();
        }
    
        public int IDNganhHoc { get; set; }
        public string TenNganh { get; set; }
        public Nullable<int> IDKhoiHoc { get; set; }
        public Nullable<int> NamDT { get; set; }
        public Nullable<int> SoKiHoc { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDT> CTDTs { get; set; }
        public virtual KhoiHoc KhoiHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHoc> LopHocs { get; set; }
    }
}
