//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.HocPhis = new HashSet<HocPhi>();
            this.KQHTs = new HashSet<KQHT>();
        }
    
        public int IDSinhVien { get; set; }
        public Nullable<int> IDLopHoc { get; set; }
        public string FullName { get; set; }
        public string Avatar { get; set; }
        public string Adress { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> Male { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Born { get; set; }
        public Nullable<int> YearJoin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocPhi> HocPhis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KQHT> KQHTs { get; set; }
        public virtual LopHoc LopHoc { get; set; }
    }
}
