//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int IDTinTuc { get; set; }
        public string TieuDe { get; set; }
        public string TomTat { get; set; }
        public string NoiDung { get; set; }
        public string LinkFile { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Image { get; set; }
        public Nullable<bool> ThongBao { get; set; }
        public Nullable<int> CountView { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
    }
}
